Repository 99z-diary/99z-diary-be-v2, pull requests merged in 2023-12, with the labels that each got.

#4 [Feat/#3] 로그인 구현
  package.json
  src/app.module.ts
  src/main.ts
  src/user/dto/user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  yarn.lock
Labels: 🖥 Feat

#6 [Feat/#5] 메인 페이지 api 구현
  src/app.module.ts
  src/post/dto/post.dto.ts
  src/post/entities/post.entity.ts
  src/post/post.controller.spec.ts
  src/post/post.controller.ts
  src/post/post.module.ts
  src/post/post.service.spec.ts
  src/post/post.service.ts
  src/schedule/dto/schedule.dto.ts
  src/schedule/entities/schedule.entity.ts
  src/schedule/schedule.controller.spec.ts
  src/schedule/schedule.controller.ts
  src/schedule/schedule.module.ts
  src/schedule/schedule.service.spec.ts
  src/schedule/schedule.service.ts
Labels: 🖥 Feat

#10 [Feat/#9] 회원가입 구현
  package.json
  src/app.module.ts
  src/signup/dto/signup.email.dto.ts
  src/signup/dto/signup.nickname.dto.ts
  src/signup/interface/emailoption.interface.ts
  src/signup/signup.controller.spec.ts
  src/signup/signup.controller.ts
  src/signup/signup.module.ts
  src/signup/signup.service.spec.ts
  src/signup/signup.service.ts
  src/user/dto/user.dto.ts
  src/user/user.repository.ts
  yarn.lock
Labels: 🖥 Feat

#12 [Feat/#11] 이메일 비밀번호 찾기 구현
  src/user/dto/user.password.dto.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: 🖥 Feat

#14 [Chore/#13] swagger 적용
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/main.ts
  src/signup/dto/signup.email.dto.ts
  src/signup/dto/signup.nickname.dto.ts
  src/signup/signup.controller.ts
  src/user/dto/user.dto.ts
  src/user/dto/user.login.dto.ts
  src/user/dto/user.login.response.dto.ts
  src/user/dto/user.password.dto.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.service.ts
  yarn.lock
Labels: 📃 Chore

#18 [Fix/#16] 일부 수정 사항 반영
  src/auth/auth.module.ts
  src/signup/signup.controller.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: 🔧 Fix

#19 Chore/#17: 템플릿 추가
  .github/ISSUE_TEMPLATE/issue-template-1Feat.md
  .github/ISSUE_TEMPLATE/issue-template-2FIx.md
  .github/ISSUE_TEMPLATE/issue-template-3Refact.md
  .github/ISSUE_TEMPLATE/issue-template-4Chore.md
  .github/ISSUE_TEMPLATE/issue-template-5Test.md
  .github/ISSUE_TEMPLATE/issue-template-6Docs.md
  .github/ISSUE_TEMPLATE/issue-template-7Config.md
Labels: 📃 Chore
